app/urls.py
from django.urls import path
from .views import agregar_producto, confirmar_pedido, eliminar_producto, home, limpiar_carrito, listar_pedidos, mis_pedidos, pagar_pedido, pago_exitoso, perfil_usuario, rechazar_pedido, restar_producto, pago, exit, register, realizar_pedido

urlpatterns = [
    path('', home, name="home"),
    path('agregar/<int:producto_id>/', agregar_producto, name="add"),
    path('eliminar/<int:producto_id>/', eliminar_producto, name="del"),
    path('restar/<int:producto_id>/', restar_producto, name="sub"),
    path('limpiar/', limpiar_carrito, name="cls"),
    path('pago/', pago, name='pago'),
    path('logout/', exit, name='exit'),
    path('register/', register, name='register'),
    path('realizar-pedido/', realizar_pedido, name='realizar_pedido'),
    path('pedidos/', listar_pedidos, name='listar_pedidos'),
    path('pedidos/confirmar/<int:pedido_id>/', confirmar_pedido, name='confirmar_pedido'),
    path('pedidos/rechazar/<int:pedido_id>/', rechazar_pedido, name='rechazar_pedido'),
    path('mis_pedidos/', mis_pedidos, name='mis_pedidos'),
    path('pagar_pedido/<int:pedido_id>/', pagar_pedido, name='pagar_pedido'),
    path('perfil/', perfil_usuario, name='perfil_usuario'),
    path('pago_exitoso/', pago_exitoso, name='pago_exitoso'),
    
]

ferramas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    cod_producto = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    fecha = models.DateField()
    img = models.ImageField(upload_to='productos', null=True)

    def __str__(self):
        return self.cod_producto

class Pedidos(models.Model):
    ESTADO_CHOICES = [
            ('pendiente', 'Pendiente'),
            ('aceptado', 'Aceptado'),
            ('rechazado', 'Rechazado'),
        ]
    fecha_pedido = models.DateField(auto_now_add=True) 
    cliente = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total = models.IntegerField()
    tipo_pago = models.CharField(max_length=50)
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='pendiente')
   
    def __str__(self):
        return f'Pedido {self.id} de {self.cliente}'
    
    def __str__(self):
        return f"Pedido {self.id} - {self.estado}"

    def productos(self):
        return self.productopedido_set.all()

class ProductoPedido(models.Model):
    pedido = models.ForeignKey(Pedidos, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    total = models.IntegerField()
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.producto)

    def to_json(self):
        item = model_to_dict(self, exclude=['created'])
        return item

app/templates/app/carrito.html
{% load humanize %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="alert alert-primary" role="alert">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="row" colspan="3" class="text-center">Carrito</th>
            </tr>
            <tr>
                <th scope="col"></th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carrito %}
            {% for key, value in request.session.carrito.items %}
            <tr>
                <td><img src="{{ value.imagen }}" alt="{{ value.nombre }}" style="width: 50px; height: auto;"></td>
                <td>{{ value.nombre }}</td>
                <td>${{ value.acumulado|intcomma }}</td>
                <td>{{ value.cantidad }}
                    <a href="{% url 'add' key %}?next={{ request.get_full_path }}" class="badge btn-dark">+</a>
                    <a href="{% url 'sub' key %}?next={{ request.get_full_path }}" class="badge btn-dark">-</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">
                <div class="alert alert-danger text-center">Sin Producto</div>
                </td>
            </tr>
            {% endif %}
            <tr>
                <th scope="row">Total</th>
                <td colspan="2">${{ total_carrito|intcomma }}</td>
            </tr>
        </tbody>
    </table>
    <hr>
</div>
<div class="row text-center">
    <div class="col-6">
        <a href="{% url 'cls' %}" class="btn btn-danger">Limpiar</a>
    </div>
    <div class="col-6">
        <a href="{% url 'pago' %}" class="btn btn-success">Ir a pagar</a>
    </div>
</div>

app/templates/app/catalogo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>catalogo</h2>
</body>
</html>

app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<body>
<header>
    {% if messages %}
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                {% for message in messages %}
                    Swal.fire({
                        icon: "{% if message.tags == 'error' %}error{% elif message.tags == 'warning' %}warning{% elif message.tags == 'success' %}success{% else %}info{% endif %}",
                        title: "{{ message }}",
                        showConfirmButton: false,
                        timer: 1000
                    });
                {% endfor %}
            });
        </script>
    {% endif %}
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                FERRAMÁS
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link nav-link-1 " aria-current="" href="">Catálogo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-link-2" href="">Contacto</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                      <i class="fas fa-shopping-cart"></i> Carrito
                      <span class="badge badge-pill badge-danger">{{ request.session.carrito|length }}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right p-3" aria-labelledby="navbarDropdown" style="min-width: 300px;">
                        {% include "app/carrito.html" %}

                    </div>
                </li>
                {% if perms.app.change_pedidos %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-2" href="{% url 'listar_pedidos' %}">Listado de pedidos</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated and not request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link nav-link-2" href="{% url 'mis_pedidos' %}">Mis pedidos</a>
                    </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user-circle fa-2x"></i> 
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{% url 'perfil_usuario' %}">Perfil</a>
                            <a class="dropdown-item" href="{% url 'exit' %}">Cerrar Sesión</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user-circle fa-2x"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{% url 'login' %}">Ingresar</a>
                            <a class="dropdown-item" href="{% url 'register' %}">Registrarse</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                "title": "",
                "text": "{{m}}"
            })
        </script>
    {% endfor %}
    {% endif %}
    <div class="tm-hero d-flex justify-content-center align-items-center" data-parallax="scroll" data-image-src="{% static 'img/banner-ferreteria.jpg' %}">
        <form class="d-flex" method="GET" action="{% url 'home' %}">
            <select name="filtro" class="tm-search-select">
                <option value="">Todos</option>
                <option value="1">Herramientas Manuales</option>
                <option value="2">Materiales Básicos</option>
                <option value="3">Equipos de Seguridad</option>
                <option value="4">Tornillos y Anclajes</option>
                <option value="5">Fijaciones y Adhesivos</option>
                <option value="6">Equipos de Medición</option>
            </select>
            <input class="form-control tm-search-input" type="search" placeholder="Buscar" name="Buscar">
            <button class="btn btn-outline-success tm-search-btn" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </div>

</header>

{% load humanize %}
<div class="container-fluid tm-container-content tm-mt-60">
    <div class="row mb-4">
        <h2 class="col-6 tm-text-primary">
            Nuevos productos
        </h2>
        <div class="col-6 d-flex justify-content-end align-items-center">
            <form action="" class="tm-text-primary">
                Página <input type="text" value="{{ productos.number }}" size="1" class="tm-input-paging tm-text-primary"> de {{ productos.paginator.num_pages }}
            </form>
        </div>
    </div>
    
        <div class="row tm-mb-90 tm-gallery">
            {% for p in productos %}
                <div class="col-xl-3 col-lg-2 col-md-4 col-sm-4 col-12 mb-5">
                    <div class="items-p">
                        <figure class="effect-ming tm-video-item">
                            {% if p.img %}
                                <img src="{{ p.img.url }}" alt="Image" class="product-image">
                            {% endif %}
                            <figcaption class="align-items-center justify-content-center">
                            </figcaption>                 
                        </figure>
                    <div class="desc_item">
                        <h3>{{ p.nombre }}</h3>
                        <h3>${{ p.precio | intcomma }}</h3>
                        <a href="{% url 'add' p.id %}" class="btn btn-primary boton-item">Agregar al carrito</a>
                    </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    
    <!-- Paginación -->
    <div class="row tm-mb-90">
        <div class="col-12 d-flex justify-content-between align-items-center tm-paging-col">
            {% if productos.has_previous %}
                <a href="?page={{ productos.previous_page_number }}&Buscar={{ request.GET.Buscar }}&filtro={{ request.GET.filtro }}" class="btn btn-primary tm-btn-prev mb-2">Anterior</a>
            {% else %}
                <a href="#" class="btn btn-primary tm-btn-prev mb-2 disabled">Anterior</a>
            {% endif %}

            <div class="tm-paging d-flex">
                {% for num in productos.paginator.page_range %}
                    {% if num == productos.number %}
                        <a href="?page={{ num }}&Buscar={{ request.GET.Buscar }}&filtro={{ request.GET.filtro }}" class="active tm-paging-link">{{ num }}</a>
                    {% else %}
                        <a href="?page={{ num }}&Buscar={{ request.GET.Buscar }}&filtro={{ request.GET.filtro }}" class="tm-paging-link">{{ num }}</a>
                    {% endif %}
                {% endfor %}
            </div>

            {% if productos.has_next %}
                <a href="?page={{ productos.next_page_number }}&Buscar={{ request.GET.Buscar }}&filtro={{ request.GET.filtro }}" class="btn btn-primary tm-btn-next">Siguiente</a>
            {% else %}
                <a href="#" class="btn btn-primary tm-btn-next disabled">Siguiente</a>
            {% endif %}
        </div>            
    </div>
</div>

    {% include "app/base/footer.html" %}

app/templates/app/listar_pedidos.html
{% include "app/base/header.html" %}
{% block js %}
<script>
    function AceptarPedido(url){
        Swal.fire({
            "title": "¿Confirmar pedido?",
            "text": "Al aceptar el pedido, se enviará la orden de compra al cliente.",
            "icon": "question",
            "showCancelButton": true,
            "cancelButtonText": "Volver",
            "confirmButtonText": "Sí, aceptar pedido",
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url; // Redirige a la URL de aceptar pedido
            }
        });
    }

    function RechazarPedido(url){
        Swal.fire({
            "title": "¿Rechazar pedido?",
            "text": "Al rechazar el pedido, se le notificará al cliente.",
            "icon": "question",
            "showCancelButton": true,
            "cancelButtonText": "Volver",
            "confirmButtonText": "Sí, rechazar pedido",
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url; // Redirige a la URL de rechazar pedido
            }
        });
    }
</script>
{% endblock %}

<main>
    <form method="post" class="mb-3">
        {% csrf_token %}
        <label for="moneda">Selecciona la moneda:</label>
        <select name="moneda" id="moneda">
            <option value="dolar">Dólar ($)</option>
            <option value="euro">Euro (€)</option>
            <option value="libra">Libra (£)</option>
            <option value="yen">Yen (¥)</option>
        </select>
        <button type="submit" class="btn btn-primary">Convertir</button>
    </form>
    <div class="container">
        <h1>Gestionar Pedidos</h1>
        <table class="pedido-table">
            <thead>
                <tr>
                    <th>ID del Pedido</th>
                    <th>Total</th>
                    <th>Fecha del Pedido</th>
                    <th>Total Conversión</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>{{ pedido.id }}</td>
                        <td>${{ pedido.total }}</td>
                        <td>{{ pedido.fecha_pedido }}</td>
                        <td align="center">
                            {% if pedido.total_convertido %}
                                <center>
                                    {{ pedido.total_convertido|floatformat:2 }}
                                    {% if pedido.moneda_seleccionada == 'dolar' %} $ 
                                    {% elif pedido.moneda_seleccionada == 'euro' %} € 
                                    {% elif pedido.moneda_seleccionada == 'libra' %} £ 
                                    {% elif pedido.moneda_seleccionada == 'yen' %} ¥ 
                                    {% endif %}
                                </center>
                            {% else %}
                                <center>No convertido</center>
                            {% endif %}
                        </td>
                        
                        <td>{{ pedido.estado }}</td>
                        <td>
                            {% if pedido.estado == 'pendiente' %}
                                <a href="#" onclick="AceptarPedido('{% url 'confirmar_pedido' pedido.id %}')" class="btn-success btn">Aceptar</a>
                                <a href="#" onclick="RechazarPedido('{% url 'rechazar_pedido' pedido.id %}')" class="btn-danger btn">Rechazar</a>
                            {% elif pedido.estado == 'aceptado' %}
                                <i class="fa fa-check-circle text-success"></i> 
                            {% elif pedido.estado == 'rechazado' %}
                                <i class="fa fa-times-circle text-danger"></i> 
                            {% elif pedido.estado == 'pagado' %}
                                <span style="color: green;">
                                    <i class="fas fa-check-circle"></i> Pagado
                                </span>    
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">No hay pedidos para gestionar.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% include "app/base/footer.html" %}

app/templates/app/mis_pedidos.html
{% include "app/base/header.html" %}
<main>
    <div class="container">
        <h1>Mis Pedidos</h1>
        <form method="post" class="mb-3">
            {% csrf_token %}
            <label for="moneda">Selecciona la moneda:</label>
            <select name="moneda" id="moneda">
                <option value="none" {% if moneda_seleccionada == "none" %}selected{% endif %}>Sin Conversión</option>
                <option value="dolar" {% if moneda_seleccionada == "dolar" %}selected{% endif %}>Dólar ($)</option>
                <option value="euro" {% if moneda_seleccionada == "euro" %}selected{% endif %}>Euro (€)</option>
                <option value="libra" {% if moneda_seleccionada == "libra" %}selected{% endif %}>Libra (£)</option>
                <option value="yen" {% if moneda_seleccionada == "yen" %}selected{% endif %}>Yen (¥)</option>
            </select>
            <button type="submit" class="btn btn-primary">Convertir</button>
        </form>

        <table class="pedido-table">
            <thead>
                <tr>
                    <th>ID del Pedido</th>
                    <th>Total</th>
                    <th>Fecha del Pedido</th>
                    <th>Estado</th>
                    <th>Método de pago</th>
                    <th>Productos</th>
                    <th>Total Convertido</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>{{ pedido.id }}</td>
                        <td>${{ pedido.total }}</td>
                        <td>{{ pedido.fecha_pedido }}</td>
                        <td>{{ pedido.estado }}</td>
                        <td>{{ pedido.tipo_pago }}</td>
                        <td>
                            <ul>
                                {% for producto in pedido.productos %}
                                    <li>{{ producto.producto.nombre }} - Cantidad: {{ producto.cantidad }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            {% if pedido.total_convertido %}
                                {{ pedido.total_convertido|floatformat:2 }} 
                                {% if pedido.moneda_seleccionada == 'dolar' %} $ 
                                {% elif pedido.moneda_seleccionada == 'euro' %} € 
                                {% elif pedido.moneda_seleccionada == 'libra' %} £ 
                                {% elif pedido.moneda_seleccionada == 'yen' %} ¥ 
                                {% endif %}
                            {% else %}
                                No convertido
                            {% endif %}
                        </td>
                        <td>
                            {% if pedido.estado == 'pagado' %}
                                <span style="color: green;">
                                    <i class="fas fa-check-circle"></i> Pagado
                                </span>
                            {% elif pedido.estado == 'aceptado' %}
                                <a href="{% url 'pagar_pedido' pedido.id %}" class="btn btn-primary">Pagar Ahora</a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="9">No tienes pedidos aún.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% include "app/base/footer.html" %}

app/templates/app/pagar_pedido.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Aca iria la API de transbank, si supiera como
</body>
</html>

app/templates/app/pago.html
{% include "app/base/header.html" %}
{% load humanize %}

{% block js %}
<script>
    function ConfirmarPedido(formId) {
        Swal.fire({
            "title": "¿Confirmar pedido?",
            "text": "Al aceptar su pedido, este pasará a ser revisado por un vendedor",
            "icon": "question",
            "showCancelButton": true,
            "cancelButtonText": "No, cancelar pedido",
            "confirmButtonText": "Sí, confirmar pedido",
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById(formId).submit();
            }
        });
    }
</script>
{% endblock %}

<form method="post" class="mb-3">
    {% csrf_token %}
    <label for="moneda">Selecciona la moneda:</label>
    <select name="moneda" id="moneda">
        <option value="dolar">Dólar ($)</option>
        <option value="euro">Euro (€)</option>
        <option value="libra">Libra (£)</option>
        <option value="yen">Yen (¥)</option>
    </select>
    <button type="submit" class="btn btn-primary">Convertir</button>
</form>

<main>
    <div align="center">
        <h1>Resumen del Pedido</h1>
    </div>
    <div class="alert alert-primary" role="alert">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th colspan="5" class="text-center">Resumen</th>
                </tr>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio</th>
                </tr>
            </thead>
            <tbody>
                {% if productos %}
                    {% for item in productos %}
                        <tr>
                            <td><img src="{{ item.producto.img.url }}" alt="{{ item.producto.nombre }}" style="width: 50px; height: auto;"></td>
                            <td>{{ item.producto.nombre }}</td>
                            <td align="right">{{ item.cantidad }}</td>
                            <td align="right">${{ item.producto.precio|intcomma }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center">
                            <div class="alert alert-danger">Sin Producto</div>
                        </td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <hr>
    </div>

    <h3 align="center">Total: ${{ total|intcomma }}</h3>
    <h3 align="center">
        {% if total_convertido %}
            Total Convertido: ${{ total_convertido|floatformat:2 }}
            {% if moneda_seleccionada == 'dolar' %} $
            {% elif moneda_seleccionada == 'euro' %} €
            {% elif moneda_seleccionada == 'libra' %} £
            {% elif moneda_seleccionada == 'yen' %} ¥
            {% endif %}
        {% else %}
            No convertido
        {% endif %}
    </h3>

    <form id="pedidoForm" method="POST" action="{% url 'realizar_pedido' %}">
        {% csrf_token %}
        <div align="center">
            <label for="tipo_pago">Tipo de pago:</label>
        </div>
        <div align="center">
            <select name="tipo_pago" required>
                <option value="tarjeta">WebPay (débito/crédito)</option>
                <option value="efectivo">Efectivo</option>
                <option value="transferencia">Transferencia</option>
            </select>
        </div>
        <br>
        <div align="center"> 
            <a href="#" onclick="ConfirmarPedido('pedidoForm')" class="btn btn-primary">Confirmar Pedido</a>
        </div>
    </form>
</main>

{% include "app/base/footer.html" %}

app/templates/app/pago_exitoso.html
{% include "app/base/header.html" %}
<main>
    <div class="container">
        <h1>Pago Exitoso</h1>
        <p>¡Gracias por tu compra!</p>
        <h2>Detalles de tu Pedido</h2>
        <ul>
            <li>ID del Pedido: {{ pedido.id }}</li>
            <li>Total: ${{ pedido.total }}</li>
            <li>Fecha del Pedido: {{ pedido.fecha_pedido }}</li>
            <li>Estado: {{ pedido.estado }}</li>
            <li>Método de Pago: {{ pedido.tipo_pago }}</li>
        </ul>
        <h3>Productos</h3>
        <ul>
            {% for producto in pedido.productopedido_set.all %} 
                <li>
                    <img src="{{ producto.producto.img.url }}" alt="{{ producto.producto.nombre }}" style="width: 100px; height: auto;">
                    {{ producto.producto.nombre }} - Cantidad: {{ producto.cantidad }}
                </li>
            {% endfor %}
        </ul>
    </div>
</main>
{% include "app/base/footer.html" %}

app/templates/app/pago_fallido.html
{% include "app/base/header.html" %}
<main>
    <div class="container">
        <h1>Pago Fallido</h1>
        <p>Lo sentimos, el pago no se ha completado.</p>
        <ul>
            <li>ID del Pedido: {{ pedido.id }}</li>
            <li>Total: ${{ pedido.total }}</li>
            <li>Estado: {{ pedido.estado }}</li>
            <li>Método de Pago: {{ pedido.tipo_pago }}</li>
        </ul>
        <h3>Productos</h3>
        <ul>
            {% for producto in pedido.productopedido_set.all %} 
                <li>
                    <img src="{{ producto.producto.img.url }}" alt="{{ producto.producto.nombre }}" style="width: 100px; height: auto;">
                    {{ producto.producto.nombre }} - Cantidad: {{ producto.cantidad }}
                </li>
            {% endfor %}
        </ul>
    </div>
</main>
{% include "app/base/footer.html" %}

app/templates/app/perfil_usuario.html
{% include "app/base/header.html" %}
<main>
    <body>
        <h1>Perfil de Usuario</h1>
    
        <p><strong>Nombre:</strong> {{ nombre }}</p>
        <p><strong>Correo:</strong> {{ correo }}</p>
    
        {% if not es_staff %}
            <p><strong>Pedidos Aceptados:</strong> {{ pedidos_aceptados }}</p>
            <p><strong>Pedidos Pagados:</strong> {{ pedidos_pagados }}</p>
        {% else %}
            <p><strong>Rol Asignado:</strong> {{ rol }}</p>
        {% endif %}
    </body>
</main>
{% include "app/base/footer.html" %}